### ISSUE TITLE
MS Teams not running

### ISSUE THREAD

**Issue by stefanoconiglio** [rafgui12/Office365WebDesktop#1]
I can't seem to be able to run Teams within Office365WebDesktop. A window opens, but it's endlessly stuck on "Microsoft Teams - Initializing...".

**Comment by marcoccio** [comment]
You can install native teams in linux

**Comment by rafgui12** [comment]
Hello, the project is a webview with DROP and DRAG functionalities for Word, Excel, PowerPoin, although the other applications come out, due to office security policies, the project does not support its entirety, sorry that for now we do not have a solution, as the user says. @marcoccio I leave you the link to download the application from snapcraft [Teams](https://snapcraft.io/teams), I hope to be of help

**Comment by fabern** [comment]
Might the Teams initialization be linked to the same problem as with the MS-365-Electron https://github.com/agam778/MS-365-Electron/issues/76. Note that the workaround presented over there seems to work.
