### ISSUE TITLE
Creating Documents not possible

### ISSUE THREAD

**Issue by julianschelb** [rafgui12/Office365WebDesktop#3]
The title basically says it all. Every method I've tried to create a new document - whether Word, Excel, or PowerPoint - fails with the following error message. The used account is an Office 365 Business Standard account, if that matters. When using a browser, this problem does not occur and it seems like everything else in the app works fine.

![image](https://user-images.githubusercontent.com/32820083/130847711-b6c49273-d8b9-4852-8850-9baac6c70b69.png)

The text is saying: 

> New documents cannot be created.
> We cannot create a new document at the moment. Please try again later.
> If this problem persists, you can try to create a new document from OneDrive.
> Korrelations-ID: 5a681466-655e-410a-9bcf-0da792784c6a

**Comment by harcel** [comment]
I have the same! Pop!_OS 21.04.

**Comment by rafgui12** [comment]
@julianschelb and @harcel, i make some changes in this 2 last release, please let me know if with version 0.6.3 or version 0.7.0 you were able to create documents, otherwise please let me know what country you are in to find out the policies and how we can solve this, please also check your space OneDrive cloud, which may be a cause of the crash, I look forward to your feedback.

**Comment by julianschelb** [comment]
Works now without an issue.
Thanks!
